/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FordFrenzyGamePresentation {
  $schema?: string;
  version: 1;
  id: string;
  layout: "conversation";
  mission: {
    brand: string;
    eyebrow: string;
    title: string;
    totalTargets: number;
  };
  /**
   * @minItems 1
   */
  assets: [
    {
      id: string;
      url: string;
      /**
       * Optional portrait presentation only. Required scene textures belong to the renderer manifest.
       */
      required: false;
    },
    ...{
      id: string;
      url: string;
      /**
       * Optional portrait presentation only. Required scene textures belong to the renderer manifest.
       */
      required: false;
    }[]
  ];
  /**
   * @minItems 1
   */
  characters: [
    {
      id: string;
      name: string;
      assetId: string;
      expressions: {
        neutral: string;
        annoyed?: string;
        amused?: string;
        surprised?: string;
      };
    },
    ...{
      id: string;
      name: string;
      assetId: string;
      expressions: {
        neutral: string;
        annoyed?: string;
        amused?: string;
        surprised?: string;
      };
    }[]
  ];
  /**
   * @minItems 1
   */
  conversations: [
    {
      id: string;
      /**
       * @minItems 1
       */
      beats: [
        {
          id: string;
          speaker: string;
          line: string;
          expression: "neutral" | "annoyed" | "amused" | "surprised";
        },
        ...{
          id: string;
          speaker: string;
          line: string;
          expression: "neutral" | "annoyed" | "amused" | "surprised";
        }[]
      ];
      title: string;
    },
    ...{
      id: string;
      /**
       * @minItems 1
       */
      beats: [
        {
          id: string;
          speaker: string;
          line: string;
          expression: "neutral" | "annoyed" | "amused" | "surprised";
        },
        ...{
          id: string;
          speaker: string;
          line: string;
          expression: "neutral" | "annoyed" | "amused" | "surprised";
        }[]
      ];
      title: string;
    }[]
  ];
  /**
   * @minItems 1
   */
  targetLabels: [
    {
      objectId: string;
      label: string;
      inspection: "brief" | "inspect";
    },
    ...{
      objectId: string;
      label: string;
      inspection: "brief" | "inspect";
    }[]
  ];
}
