/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Text = string;
export type ReviewDate = string;

export interface Scene {
  version: 1;
  id: Id;
  width: number;
  height: number;
  /**
   * @minItems 1
   */
  objects: [SceneObject, ...SceneObject[]];
  /**
   * @minItems 1
   */
  vocabulary: [VocabularyRecord, ...VocabularyRecord[]];
  completion: CompletionRule;
}
export interface SceneObject {
  id: Id;
  x: number;
  y: number;
  width: number;
  height: number;
  vocabularyId: Id;
}
export interface VocabularyRecord {
  id: Id;
  text: Text;
  meaning: Text;
  dialect: Text;
  source: Text;
  attribution: Text;
  permittedUse: Text;
  approval: ContentApproval;
}
export interface ContentApproval {
  status: "fixture" | "draft" | "approved";
  reviewedBy?: Text;
  reviewedOn?: ReviewDate;
}
export interface CompletionRule {
  type: "find-all";
  /**
   * @minItems 1
   */
  requiredIds: [Id, ...Id[]];
}
