/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Text = string;
export type ReviewDate = string;

export interface SceneV2 {
  version: 2;
  id: Id;
  width: number;
  height: number;
  /**
   * @minItems 1
   */
  objects: [SceneObjectV2, ...SceneObjectV2[]];
  /**
   * @minItems 1
   */
  contents: [InvestigativeContent, ...InvestigativeContent[]];
  sources: SourceRecord[];
  completion: CompletionRuleV2;
}
export interface SceneObjectV2 {
  id: Id;
  x: number;
  y: number;
  width: number;
  height: number;
  contentId: Id;
}
export interface InvestigativeContent {
  id: Id;
  label: Text;
  clueId: Id;
  classification: "fact" | "allegation" | "fiction";
  sourceRefs: Id[];
  editorial: EditorialMetadata;
  rights: RightsMetadata;
}
export interface EditorialMetadata {
  status: "fixture" | "draft" | "reviewed" | "approved";
  reviewedBy?: Text;
  reviewedOn?: ReviewDate;
  notes?: Text;
}
export interface RightsMetadata {
  status: "fixture" | "unresolved" | "cleared";
  basis: Text;
  attribution?: Text;
}
export interface SourceRecord {
  id: Id;
  title: Text;
  url: string;
  publishedOn: ReviewDate;
}
export interface CompletionRuleV2 {
  type: "find-all";
  /**
   * @minItems 1
   */
  requiredIds: [Id, ...Id[]];
}
